kind: pipeline
type: docker
name: build

clone:
  depth: 1

steps:
- name: cooked
  image: kry9ton/image:latest
  environment:
    token:
      from_secret: bot_api
    github_cert:
      from_secret: github_cert
    SF_PASS:
      from_secret: sf_pass
    DEVICE: miatoll
    POST_DIR: miatoll
    RELEASE: true
    CODENAME: Kryogen
    TYPE: BLC
    CHANGELOG: |
      Merge kernel tag 4.14.207
      Update sdfat driver v2.4.5
      Fix GPU latency for high frame rate
      Adding conservative governor v2
      Base from A10 Kernel Joyeuse
      Support A12 (Tested on Komodo OS A12)
  commands:
  - git clone https://github.com/Kry9toN-Project/Drone-CI
  - mv Drone-CI/* .
  - bash main.sh
