kind: pipeline
type: docker
name: build

clone:
  depth: 1

steps:
- name: cooked
  image: kry9ton/image:latest
  environment:
    token:
      from_secret: bot_api
    github_cert:
      from_secret: github_cert
    SF_PASS:
      from_secret: sf_pass
    DEVICE: miatoll
    POST_DIR: miatoll
    RELEASE: false
    CODENAME: Kryogen
    TYPE: BLC
    CHANGELOG: |
      Merge last 4.14.x version
  commands:
  - git clone https://github.com/Kry9toN-Project/Drone-CI
  - mv Drone-CI/* .
  - bash main.sh
