version: 2
jobs:
  nightly:
    docker:
      - image: kry9ton/image:latest
        environment:
          DEVICE: miatoll
          CODENAME: HackTon
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/Kry9toN-Project/Drone-CI
            mv Drone-CI/* .
            bash nightly.sh
  build:
    resource_class: large
    docker:
      - image: kry9ton/image:latest
        environment:
          DEVICE: miatoll
          POST_DIR: miatoll
          RELEASE: false
          CODENAME: HackTon
          TYPE: HCK
          CHANGELOG: • Base on BLC version<br>• Support wifi injection<br>• Support rtl88xxau and rtl8xxxu<br>• All change for nethunter device kernel
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/Kry9toN-Project/Drone-CI
            mv Drone-CI/* .
            bash main.sh

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - nightly
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - main
