version: 2
jobs:
  nightly:
    docker:
      - image: kry9ton/image:latest
        environment:
          DEVICE: miatoll
          CODENAME: Track
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/Kry9toN-Project/Drone-CI
            mv Drone-CI/* .
            bash nightly.sh
  build:
    resource_class: large
    docker:
      - image: kry9ton/image:latest
        environment:
          DEVICE: miatoll
          POST_DIR: miatoll
          RELEASE: false
          CODENAME: Track
          TYPE: BLC
          CHANGELOG: |
            Rebase to caf source thanks to @dreadnoughtOO7
            Support KernelSU 11089
            Support DriveDroid apps
            This initial release from new base
            Tested on A13
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/Kry9toN-Project/Drone-CI
            mv Drone-CI/* .
            bash main.sh

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    jobs:
      - nightly
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - BLC
